# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\gitee\knowledge\Python\yys_script\test\match_im\match_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_match_win(object):
    def setupUi(self, match_win):
        match_win.setObjectName("match_win")
        match_win.resize(359, 460)
        self.centralwidget = QtWidgets.QWidget(match_win)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 351, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pbtn_dir = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pbtn_dir.setObjectName("pbtn_dir")
        self.horizontalLayout_6.addWidget(self.pbtn_dir)
        self.le_dir = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.le_dir.setText("")
        self.le_dir.setObjectName("le_dir")
        self.horizontalLayout_6.addWidget(self.le_dir)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.le_win = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.le_win.setObjectName("le_win")
        self.horizontalLayout.addWidget(self.le_win)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pbt_start = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pbt_start.setObjectName("pbt_start")
        self.verticalLayout_2.addWidget(self.pbt_start)
        self.pbtn_stop = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pbtn_stop.setObjectName("pbtn_stop")
        self.verticalLayout_2.addWidget(self.pbtn_stop)
        self.te_log = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.te_log.setObjectName("te_log")
        self.verticalLayout_2.addWidget(self.te_log)
        self.btn_clear = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_2.addWidget(self.btn_clear)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(5, 8)
        match_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(match_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 359, 23))
        self.menubar.setObjectName("menubar")
        match_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(match_win)
        self.statusbar.setObjectName("statusbar")
        match_win.setStatusBar(self.statusbar)

        self.retranslateUi(match_win)
        self.pbtn_dir.clicked.connect(match_win.slot_btn_dir_clicked)
        self.pbt_start.clicked['bool'].connect(match_win.slot_btn_start_clicked)
        self.pbtn_stop.clicked.connect(match_win.slot_btn_stop_clicked)
        self.btn_clear.clicked.connect(self.te_log.clear)
        self.pbtn_dir.released.connect(match_win.slot_btn_dir_released)
        QtCore.QMetaObject.connectSlotsByName(match_win)

    def retranslateUi(self, match_win):
        _translate = QtCore.QCoreApplication.translate
        match_win.setWindowTitle(_translate("match_win", "图片匹配工具"))
        self.pbtn_dir.setText(_translate("match_win", "选择文件"))
        self.label_5.setText(_translate("match_win", "选择窗体:"))
        self.le_win.setText(_translate("match_win", "阴阳师-网易游戏"))
        self.pbt_start.setText(_translate("match_win", "开始匹配"))
        self.pbtn_stop.setText(_translate("match_win", "停止匹配"))
        self.te_log.setHtml(_translate("match_win", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">匹配的日志</p></body></html>"))
        self.btn_clear.setText(_translate("match_win", "清空内容"))
